import "./globals.css";
import type { Metadata } from "next";
import Navbar from "@/components/UI/Navbar/Navbar";
import { UserProvider } from "@/stores/UserContext";
import RegisterModal from "@/components/UI/Modals/RegisterModal/RegisterModal";
import { ModalProvider } from "@/providers/ModalProvider";
import Footer from "@/components/UI/Footer/Footer";
import LoginModal from "@/components/UI/Modals/LoginModal/LoginModal";

export const metadata: Metadata = {
  title: "AptSmart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <UserProvider>
      <ModalProvider> 
        <Navbar />
        <RegisterModal />
        <LoginModal />
        <html lang="en">
            <body>
              {children}
            </body>
        </html>
        <Footer />
      </ModalProvider>
    </UserProvider>
  );
}
